name: GoldmanEnchants
main: lee.code.enchants.GoldmanEnchants
version: ${project.version}
api-version: 1.19
author: Lee
depend: [GoldmanChunks, GoldmanPets, GoldmanEssentials, CoreProtect, GoldmanCore]
commands:
  customenchant:
    description: Add a custom enchant to your hand item.
    permission: enchants.command.enchant
    aliases: [cenchant]
    usage: "/customenchants &f<enchantment>"