package lee.code.enchants.lists;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.bukkit.Material;

@AllArgsConstructor
public enum ShovelDestroyerBlocks {

    GRASS_BLOCK(Material.GRASS_BLOCK),
    DIRT(Material.DIRT),
    COARSE_DIRT(Material.COARSE_DIRT),
    PODZOL(Material.PODZOL),
    ROOTED_DIRT(Material.ROOTED_DIRT),
    CRIMSON_NYLIUM(Material.CRIMSON_NYLIUM),
    WARPED_NYLIUM(Material.WARPED_NYLIUM),
    SAND(Material.SAND),
    RED_SAND(Material.RED_SAND),
    CLAY(Material.CLAY),
    GRAVEL(Material.GRAVEL),
    DIRT_PATH(Material.DIRT_PATH),
    WHITE_CONCRETE_POWDER(Material.WHITE_CONCRETE_POWDER),
    ORANGE_CONCRETE_POWDER(Material.ORANGE_CONCRETE_POWDER),
    MAGENTA_CONCRETE_POWDER(Material.MAGENTA_CONCRETE_POWDER),
    LIGHT_BLUE_CONCRETE_POWDER(Material.LIGHT_BLUE_CONCRETE_POWDER),
    YELLOW_CONCRETE_POWDER(Material.YELLOW_CONCRETE_POWDER),
    LIME_CONCRETE_POWDER(Material.LIME_CONCRETE_POWDER),
    PINK_CONCRETE_POWDER(Material.PINK_CONCRETE_POWDER),
    GRAY_CONCRETE_POWDER(Material.GRAY_CONCRETE_POWDER),
    LIGHT_GRAY_CONCRETE_POWDER(Material.LIGHT_GRAY_CONCRETE_POWDER),
    CYAN_CONCRETE_POWDER(Material.CYAN_CONCRETE_POWDER),
    PURPLE_CONCRETE_POWDER(Material.PURPLE_CONCRETE_POWDER),
    BLUE_CONCRETE_POWDER(Material.BLUE_CONCRETE_POWDER),
    BROWN_CONCRETE_POWDER(Material.BROWN_CONCRETE_POWDER),
    GREEN_CONCRETE_POWDER(Material.GREEN_CONCRETE_POWDER),
    RED_CONCRETE_POWDER(Material.RED_CONCRETE_POWDER),
    BLACK_CONCRETE_POWDER(Material.BLACK_CONCRETE_POWDER),
    SNOW_BLOCK(Material.SNOW_BLOCK),
    SOUL_SAND(Material.SOUL_SAND),
    SOUL_SOIL(Material.SOUL_SOIL),
    MUD(Material.MUD),

    ;

    @Getter private final Material block;
}
